In [1]:
!pip install nltk

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [5]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [6]:
# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [10]:
# tokenize
tokens = word_tokenize(document.lower())

In [12]:
# build vocab
vocab = {'<unk>': 0}

for token in Counter(tokens).keys():
    if token not in vocab:
        vocab[token] = len(vocab)


In [13]:
len(vocab)

289

In [14]:
# extract sentences from data

input_sentences = document.split('\n')

In [17]:
def text_to_indices(sentence, vocab):

    numerical_sentence = []

    for token in sentence:
        if token in vocab:
            numerical_sentence.append(vocab[token])
        else:
          numerical_sentence.append(0)

    return numerical_sentence


In [18]:
input_numerical_sentences = []

for sentences in input_sentences:
    input_numerical_sentences.append(text_to_indices(word_tokenize(sentences.lower()), vocab))



In [20]:
training_sequence = []

for sentence in input_numerical_sentences:

    for i in range(1, len(sentence)):
        training_sequence.append(sentence[:i+1])

In [21]:
len(training_sequence)

942

In [22]:
len_list = []

for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

62

In [25]:
padded_training_sequence = []

for sequence in training_sequence:
    padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [27]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [28]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [29]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:, -1]

In [30]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [31]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [32]:
class CustomDataset(Dataset):

  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return len(self.X)

  def __getitem__(self, index):
     return self.X[index], self.y[index]


In [33]:
dataset = CustomDataset(X, y)

In [34]:
len(dataset)

942

In [37]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [77]:
class LSTMModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, 100)
        self.lstm = nn.LSTM(100, 150, batch_first=True)
        self.fc = nn.Linear(150, vocab_size)

    def forward(self, x):
        embedded = self.embedding(x)
        intermediate_hidden_states, (final_hidden_states, final_cell_state) = self.lstm(embedded)
        return self.fc(final_hidden_states.squeeze(0))


In [78]:
model = LSTMModel(len(vocab))

In [79]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [80]:
model.to(device)

LSTMModel(
  (embedding): Embedding(289, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [84]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [88]:
for epoch in range(epochs):

  total_loss = 0

  for batch_x, batch_y in dataloader:

      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      optimizer.zero_grad()

      output = model(batch_x)

      loss = criterion(output, batch_y)

      loss.backward()

      optimizer.step()

      total_loss += loss.item()

  print(f'Epoch: {epoch}, Loss: {total_loss}')

Epoch: 0, Loss: 4.329709392040968
Epoch: 1, Loss: 4.264640260487795
Epoch: 2, Loss: 4.214858718216419
Epoch: 3, Loss: 4.2168312035501
Epoch: 4, Loss: 4.0714639313519
Epoch: 5, Loss: 4.216001819819212
Epoch: 6, Loss: 4.101224090903997
Epoch: 7, Loss: 3.9260716885328293
Epoch: 8, Loss: 4.050348483026028
Epoch: 9, Loss: 3.9138047341257334
Epoch: 10, Loss: 3.8792049288749695
Epoch: 11, Loss: 3.8941158168017864
Epoch: 12, Loss: 3.8321736864745617
Epoch: 13, Loss: 3.8118420392274857
Epoch: 14, Loss: 3.756188653409481
Epoch: 15, Loss: 3.66501341201365
Epoch: 16, Loss: 3.8190018702298403
Epoch: 17, Loss: 3.83155738376081
Epoch: 18, Loss: 3.599072987213731
Epoch: 19, Loss: 3.5987470224499702
Epoch: 20, Loss: 3.504447501152754
Epoch: 21, Loss: 3.5191734675318003
Epoch: 22, Loss: 3.4901032261550426
Epoch: 23, Loss: 3.5407615769654512
Epoch: 24, Loss: 3.5812605936080217
Epoch: 25, Loss: 3.489734284579754
Epoch: 26, Loss: 3.5216825176030397
Epoch: 27, Loss: 3.690955802798271
Epoch: 28, Loss: 3.5410

In [107]:
def predict(model, vocab, text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())

  # text to numerical indices
  numerical_text = text_to_indices(tokenized_text, vocab)

  # padding
  padded_numerical_text = [0]*(max(len_list) - len(numerical_text) - 1) + numerical_text

  # send to model
  input_tensor = torch.tensor(padded_numerical_text, dtype=torch.long).unsqueeze(0).to(device)
  output = model(input_tensor)

  # predicted index
  value, index = torch.max(output, dim=1)

  return text + " " + list(vocab.keys())[index]



In [108]:
predict(model, vocab, 'My name is')

'My name is the'

In [112]:
import time

num_tokens = 10
input_text = 'You can'

for i in range(num_tokens):
  output_text = predict(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)

You can mail
You can mail us
You can mail us at
You can mail us at nitish.campusx
You can mail us at nitish.campusx @
You can mail us at nitish.campusx @ gmail.com
You can mail us at nitish.campusx @ gmail.com gmail.com
You can mail us at nitish.campusx @ gmail.com gmail.com a
You can mail us at nitish.campusx @ gmail.com gmail.com a part
You can mail us at nitish.campusx @ gmail.com gmail.com a part of


In [67]:
# x = nn.Embedding(289, 100)
# y = nn.LSTM(100, 150, batch_first=True)
# z = nn.Linear(150, 289)

In [68]:
# a = dataset[0][0].unsqueeze(0)

In [69]:
# b = x(a)
# b

In [70]:
# b.shape

In [71]:
# c, d = y(b)

In [72]:
# c.shape

In [73]:
# e, f = d


In [74]:
# e.shape

In [75]:
# f.shape

In [76]:
# z(f.squeeze(0)).shape