In [ ]:
import torch

In [ ]:
x = torch.tensor(3.0, requires_grad=True)

In [ ]:
y = x**2

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
import math

In [ ]:
x = torch.tensor(3.0, requires_grad=True)

In [ ]:
y = x**2

In [ ]:
z = torch.sin(y)

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

<h2> Neural Network </h2>

In [ ]:
# Inputs

x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [ ]:
def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction, epsilon, 1-epsilon)
  loss = - (target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))
  return loss

In [ ]:
z = w*x + b
y_pred = torch.sigmoid(z)

loss = binary_cross_entropy_loss(y_pred, y)

In [ ]:
dloss_dy_pred = (y_pred - y) / (y_pred * (1 - y_pred))

dy_pred_dz = y_pred * (1 - y_pred)

dz_dw = x

dz_db = 1

dloss_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dloss_db = dloss_dy_pred * dy_pred_dz * dz_db

In [ ]:
print(f"Manual gradient loss wrt w: {dloss_dw}")
print(f"Manual gradient loss wrt b: {dloss_db}")

Manual gradient loss wrt w: 6.691762447357178
Manual gradient loss wrt b: 0.998770534992218


In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)


In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
b

tensor(0., requires_grad=True)

In [ ]:
z = w * x + b
z


tensor(6.7000, grad_fn=<AddBackward0>)

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y =  (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
x.grad.zero_()

tensor([0., 0., 0.])

In [ ]:
# Option 1 requires_grad_(False)
# Option 2 detach()
# OPtion 3 torch.no

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

In [ ]:
y = x ** 2
y

tensor([1., 4., 9.], grad_fn=<PowBackward0>)

In [ ]:
x.requires_grad_(False)


tensor([1., 2., 3.])

In [ ]:
y = x ** 2
y

tensor([1., 4., 9.])

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
z = x.detach()
z

tensor([1., 2., 3.])

In [ ]:
y = x ** 2
y

tensor([1., 4., 9.], grad_fn=<PowBackward0>)

In [ ]:
y1 = z ** 2
y1

tensor([1., 4., 9.])

In [ ]:
with torch.no_grad():
  y = x ** 2


In [ ]:
y

tensor([1., 4., 9.])