In [5]:
# create model
import torch
import torch.nn as nn

In [6]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [7]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.3745],
        [0.4171],
        [0.3692],
        [0.3989],
        [0.3795],
        [0.3767],
        [0.3926],
        [0.3895],
        [0.3557],
        [0.3469]], grad_fn=<SigmoidBackward0>)

In [9]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-2.4891e-04, -1.4373e-01,  2.1386e-01, -2.6600e-01, -2.4731e-02]],
       requires_grad=True)

In [10]:
model.linear.bias

Parameter containing:
tensor([-0.3248], requires_grad=True)

In [11]:
!pip install torchinfo

In [12]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [26]:
class Model1(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn. Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out


In [27]:
features = torch.rand(10, 5)

model1 = Model1(features.shape[1])

model1(features)

tensor([[0.5888],
        [0.5883],
        [0.5834],
        [0.5858],
        [0.5902],
        [0.6048],
        [0.5893],
        [0.5926],
        [0.5911],
        [0.5752]], grad_fn=<SigmoidBackward0>)

In [28]:
summary(model1, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00